[build]
  base = "/"
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
