export const GET_IMG = 'get_img'
export const GET_INDEX = 'get_index'
export const SET_IMG = 'set_img'
export const UPDATE_IMG = 'update_img'
export const GET_IMG_MINI = 'get_img_mini'
export const GET_IMG_BODY = 'get_img_body'
export const GET_IMG_PAGENEW = 'get_img_pagenew'
export const UPDATE_LINK_YOUTUBE = 'update_link_youtube'
